name: Jbake-WorkFlow
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: "Set up JDK 11 "
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "11"
      -
        name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      -
        name: "Build with Gradle"
        run: "./gradlew bake"
      -
        name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          BRANCH: gh-pages
          FOLDER: build
#          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
